// ============================================
// File: crates/aeronyx-core/src/protocol/blind_vault_replica_workflow/
//       bound_dispatch/onion_transport.rs
// ============================================
//! Verified onion-route adapter for ordered Blind Vault terminal effects.
//!
//! ## Creation Reason
//! The ordered send sequence should not depend on HTTP, QUIC, or one route
//! selector. It still needs a safe composition that turns exact payload bytes
//! into a descriptor-authenticated onion envelope before any I/O adapter sees it.
//!
//! ## Main Functionality
//! - Defines replaceable route-provider and opaque-envelope sender traits.
//! - Requires a nonzero per-send route id and source timestamp.
//! - Rechecks route purpose at the payload/envelope construction boundary.
//! - Enforces permit-authorized terminal identity before envelope construction.
//! - Builds a path-derived-TTL envelope through `VerifiedOnionRoute`.
//! - Gives the sender only entry-node identity and opaque onion bytes.
//! - Redacts route-provider and sender errors from standard diagnostics.
//!
//! ## Dependencies
//! - `send_sequence.rs`: trusted exact-effect transport boundary.
//! - `VerifiedOnionRoute`: signed descriptor and capability admission.
//! - `BlindRelayEnvelope`: existing opaque node-to-node transport object.
//! - `IdentityKeyPair`: source signature and onion envelope identity.
//!
//! ## Main Logical Flow
//! 1. Ask the route provider for fresh material for one exact effect purpose.
//! 2. Reject purpose mismatch before touching payload construction.
//! 3. Enforce any source lifecycle-authorized terminal node binding.
//! 4. Build the signed onion envelope with path-derived TTL.
//! 5. Pass only the opaque envelope to the selected transport sender.
//!
//! ## Important Note For The Next Developer
//! - Route providers must enforce liveness, diversity, and anti-affinity policy.
//! - Route ids must be fresh and unlinkable; never derive them from work ids.
//! - Do not pass plaintext payload or purpose to the envelope sender.
//! - Never ignore `context.authorized_terminal_node_id()` during selection.
//! - Endpoint retry policy belongs to the sender and route provider composition.
//!
//! Last Modified: v1.2.0-PrivacySafeTransportDiagnostics - Replaced generic
//! route/sender Debug and Display output with stable classifications.
//! v1.1.0-AuthorizedTerminalBinding - Enforced exact terminal
//! selection for workflow-permitted lifecycle operations.
//! v1.0.0-VerifiedOnionEffectTransport - Initial route/provider,
//! envelope construction, and opaque sender composition.
//! ============================================

use std::{error::Error, fmt};

use super::send_sequence::{
    BlindVaultReplicaTerminalEffectTransport, BlindVaultReplicaTerminalSendContext,
};
use crate::crypto::keys::IdentityKeyPair;
use crate::protocol::chat::BlindRelayEnvelope;
use crate::protocol::onion::{OnionRoutePlanError, OnionRoutePurpose, VerifiedOnionRoute};

/// Fresh route material selected for one exact terminal effect.
pub struct BlindVaultReplicaOnionDispatchPlan {
    route: VerifiedOnionRoute,
    route_id: [u8; 16],
    dispatched_at: u64,
}

impl BlindVaultReplicaOnionDispatchPlan {
    /// Creates bounded, nonzero source dispatch material.
    pub fn new(route: VerifiedOnionRoute, route_id: [u8; 16], dispatched_at: u64) -> Option<Self> {
        if route_id == [0; 16] || dispatched_at == 0 {
            return None;
        }
        Some(Self {
            route,
            route_id,
            dispatched_at,
        })
    }

    /// Descriptor-authenticated route selected for the effect.
    #[must_use]
    pub const fn route(&self) -> &VerifiedOnionRoute {
        &self.route
    }

    /// Unlinkable route correlation id generated by the source adapter.
    #[must_use]
    pub const fn route_id(&self) -> [u8; 16] {
        self.route_id
    }

    /// Source time used for route freshness and envelope signature.
    #[must_use]
    pub const fn dispatched_at(&self) -> u64 {
        self.dispatched_at
    }
}

impl fmt::Debug for BlindVaultReplicaOnionDispatchPlan {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("BlindVaultReplicaOnionDispatchPlan")
            .field("purpose", &self.route.purpose())
            .field("hop_count", &self.route.hop_count())
            .field("dispatched_at", &self.dispatched_at)
            .field("route_id", &"[REDACTED]")
            .finish_non_exhaustive()
    }
}

/// Replaceable source policy that selects one verified route per effect.
pub trait BlindVaultReplicaOnionRouteProvider {
    type Error;

    /// Returns fresh route material without receiving payload bytes.
    ///
    /// When `context.authorized_terminal_node_id()` is present, implementations
    /// should select that exact terminal. The transport independently rejects
    /// a returned route that does not satisfy this source authorization.
    fn route_for_terminal_effect(
        &mut self,
        context: BlindVaultReplicaTerminalSendContext,
        purpose: OnionRoutePurpose,
    ) -> Result<BlindVaultReplicaOnionDispatchPlan, Self::Error>;
}

/// Replaceable I/O boundary that receives only a complete opaque envelope.
pub trait BlindVaultReplicaOnionEnvelopeSender {
    type Response;
    type Error;

    /// Sends to the route entry. Purpose and terminal remain onion-hidden.
    fn send_onion_envelope(
        &mut self,
        context: BlindVaultReplicaTerminalSendContext,
        entry_node_id: [u8; 32],
        envelope: BlindRelayEnvelope,
    ) -> Result<Self::Response, Self::Error>;
}

/// Composition of source identity, verified route policy, and opaque I/O.
pub struct BlindVaultReplicaVerifiedOnionTransport<'identity, Routes, Sender> {
    identity: &'identity IdentityKeyPair,
    routes: Routes,
    sender: Sender,
}

impl<'identity, Routes, Sender> BlindVaultReplicaVerifiedOnionTransport<'identity, Routes, Sender> {
    /// Creates an effect transport without performing route selection or I/O.
    pub const fn new(identity: &'identity IdentityKeyPair, routes: Routes, sender: Sender) -> Self {
        Self {
            identity,
            routes,
            sender,
        }
    }

    /// Transfers replaceable policy and sender adapters back to their owner.
    #[must_use]
    pub fn into_adapters(self) -> (Routes, Sender) {
        (self.routes, self.sender)
    }
}

impl<Routes, Sender> BlindVaultReplicaTerminalEffectTransport
    for BlindVaultReplicaVerifiedOnionTransport<'_, Routes, Sender>
where
    Routes: BlindVaultReplicaOnionRouteProvider,
    Sender: BlindVaultReplicaOnionEnvelopeSender,
{
    type Response = Sender::Response;
    type Error = BlindVaultReplicaVerifiedOnionTransportError<Routes::Error, Sender::Error>;

    fn send_terminal_effect(
        &mut self,
        context: BlindVaultReplicaTerminalSendContext,
        purpose: OnionRoutePurpose,
        payload: &[u8],
    ) -> Result<Self::Response, Self::Error> {
        let plan = self
            .routes
            .route_for_terminal_effect(context, purpose)
            .map_err(BlindVaultReplicaVerifiedOnionTransportError::RouteProvider)?;
        if plan.route.purpose() != purpose {
            return Err(BlindVaultReplicaVerifiedOnionTransportError::PurposeMismatch);
        }
        if context
            .authorized_terminal_node_id()
            .is_some_and(|node_id| plan.route.terminal_node_id() != node_id)
        {
            return Err(BlindVaultReplicaVerifiedOnionTransportError::TerminalIdentityMismatch);
        }
        let entry_node_id = plan.route.entry_node_id();
        let envelope = plan
            .route
            .build_envelope(payload, plan.route_id, plan.dispatched_at, self.identity)
            .map_err(BlindVaultReplicaVerifiedOnionTransportError::RoutePlan)?;
        // [BLIND-VAULT-OPAQUE-SENDER-CONTEXT 2026-08-29 by Codex] Terminal
        // authorization is source route-policy input. Strip it before handing
        // context to the transport-only sender so onion destination remains
        // hidden behind the opaque envelope boundary.
        let sender_context = context.without_terminal_authorization();
        self.sender
            .send_onion_envelope(sender_context, entry_node_id, envelope)
            .map_err(BlindVaultReplicaVerifiedOnionTransportError::Sender)
    }
}

impl<Routes, Sender> fmt::Debug for BlindVaultReplicaVerifiedOnionTransport<'_, Routes, Sender> {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("BlindVaultReplicaVerifiedOnionTransport")
            .field("identity", &"[REDACTED]")
            .field("route_provider", &std::any::type_name::<Routes>())
            .field("sender", &std::any::type_name::<Sender>())
            .finish_non_exhaustive()
    }
}

/// Fail-closed route selection, envelope construction, or I/O error.
pub enum BlindVaultReplicaVerifiedOnionTransportError<RouteError, SenderError> {
    /// Route provider could not produce fresh policy-compliant material.
    RouteProvider(RouteError),
    /// Provider returned a route admitted for a different terminal purpose.
    PurposeMismatch,
    /// Provider selected a terminal different from workflow authorization.
    TerminalIdentityMismatch,
    /// Verified route expired, identity changed, or encryption failed.
    RoutePlan(OnionRoutePlanError),
    /// Opaque envelope I/O failed after successful local construction.
    Sender(SenderError),
}

impl<RouteError, SenderError> fmt::Display
    for BlindVaultReplicaVerifiedOnionTransportError<RouteError, SenderError>
{
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::RouteProvider(_) => formatter.write_str("blind vault route provider failed"),
            Self::PurposeMismatch => {
                formatter.write_str("blind vault onion route purpose mismatched")
            }
            Self::TerminalIdentityMismatch => {
                formatter.write_str("blind vault onion route terminal identity mismatched")
            }
            Self::RoutePlan(_) => formatter.write_str("blind vault onion route plan failed"),
            Self::Sender(_) => formatter.write_str("blind vault onion envelope sender failed"),
        }
    }
}

impl<RouteError, SenderError> fmt::Debug
    for BlindVaultReplicaVerifiedOnionTransportError<RouteError, SenderError>
{
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::RouteProvider(_) => formatter.write_str("RouteProvider(<redacted>)"),
            Self::PurposeMismatch => formatter.write_str("PurposeMismatch"),
            Self::TerminalIdentityMismatch => formatter.write_str("TerminalIdentityMismatch"),
            Self::RoutePlan(_) => formatter.write_str("RoutePlan(<redacted>)"),
            Self::Sender(_) => formatter.write_str("Sender(<redacted>)"),
        }
    }
}

impl<RouteError, SenderError> Error
    for BlindVaultReplicaVerifiedOnionTransportError<RouteError, SenderError>
where
    RouteError: Error + 'static,
    SenderError: Error + 'static,
{
    fn source(&self) -> Option<&(dyn Error + 'static)> {
        match self {
            Self::RouteProvider(error) => Some(error),
            Self::RoutePlan(error) => Some(error),
            Self::Sender(error) => Some(error),
            Self::PurposeMismatch | Self::TerminalIdentityMismatch => None,
        }
    }
}
