// ============================================
// File: crates/aeronyx-core/src/protocol/discovery/gossip.rs
// ============================================
//! # Discovery bootstrap snapshots and gossip
//!
//! Owns the JSON bootstrap snapshot of signed descriptors and the bounded
//! `NodeDiscoveryMessage` gossip envelope with its codec and endpoint
//! attestation carrier validation.
//!
//! [ARCH-SPLIT 2026-10-10 by Claude] Split from protocol/discovery.rs; bodies unchanged.

use serde::{Deserialize, Serialize};

use crate::error::CoreError;
use crate::protocol::codec::{decode_bincode_bounded, encode_bincode_bounded, TrailingBytesPolicy};
use crate::protocol::discovery_endpoint_attestation::{
    DiscoveryEndpointEvidenceAttestationV1, DISCOVERY_ENDPOINT_ATTESTATION_FRAME_BYTES_V1,
};

use super::descriptor::SignedNodeDescriptor;
use super::inclusion_proof::DirectoryDescriptorInclusionProofV1;

/// Current bootstrap snapshot schema version.
pub const NODE_BOOTSTRAP_SNAPSHOT_SCHEMA_VERSION: u16 = 1;

/// Maximum accepted JSON bootstrap snapshot size.
const MAX_BOOTSTRAP_SNAPSHOT_BYTES: usize = 512 * 1024;

/// Maximum accepted binary discovery gossip message size.
const MAX_DISCOVERY_MESSAGE_BYTES: u64 = 512 * 1024;

// ============================================
// NodeBootstrapSnapshot
// ============================================

/// JSON-friendly bootstrap list of signed node descriptors.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct NodeBootstrapSnapshot {
    /// Snapshot schema version.
    pub schema_version: u16,
    /// Unix timestamp in seconds when the snapshot was generated.
    pub generated_at: u64,
    /// Signed node descriptors included in this snapshot.
    pub peers: Vec<SignedNodeDescriptor>,
}

impl NodeBootstrapSnapshot {
    /// Creates a bootstrap snapshot with the current schema version.
    #[must_use]
    pub fn new(generated_at: u64, peers: Vec<SignedNodeDescriptor>) -> Self {
        Self {
            schema_version: NODE_BOOTSTRAP_SNAPSHOT_SCHEMA_VERSION,
            generated_at,
            peers,
        }
    }

    /// Parses a bounded JSON bootstrap snapshot.
    ///
    /// # Errors
    /// Returns `CoreError::MessageTooLarge` when input exceeds the bootstrap
    /// cap, or `CoreError::MalformedMessage` when JSON/schema parsing fails.
    pub fn from_json_bytes(bytes: &[u8]) -> Result<Self, CoreError> {
        if bytes.len() > MAX_BOOTSTRAP_SNAPSHOT_BYTES {
            return Err(CoreError::MessageTooLarge {
                max: MAX_BOOTSTRAP_SNAPSHOT_BYTES,
                actual: bytes.len(),
            });
        }

        let snapshot: Self = serde_json::from_slice(bytes)
            .map_err(|err| CoreError::malformed(format!("bootstrap snapshot json: {err}")))?;
        snapshot.validate_schema()?;
        Ok(snapshot)
    }

    /// Serializes this snapshot to pretty JSON for operator-readable bootstrap files.
    ///
    /// # Errors
    /// Returns `CoreError::MalformedMessage` if JSON serialization fails.
    pub fn to_json_pretty(&self) -> Result<Vec<u8>, CoreError> {
        serde_json::to_vec_pretty(self)
            .map_err(|err| CoreError::malformed(format!("bootstrap snapshot json: {err}")))
    }

    /// Validates the snapshot schema version.
    ///
    /// # Errors
    /// Returns `CoreError::MalformedMessage` for unsupported schema versions.
    pub fn validate_schema(&self) -> Result<(), CoreError> {
        if self.schema_version != NODE_BOOTSTRAP_SNAPSHOT_SCHEMA_VERSION {
            return Err(CoreError::malformed(format!(
                "unsupported bootstrap snapshot schema version: {}",
                self.schema_version
            )));
        }
        Ok(())
    }

    /// Counts descriptors that verify at `now`.
    ///
    /// This is intentionally non-mutating. Server-side stores decide whether
    /// to reject, keep, or report invalid descriptors.
    #[must_use]
    pub fn verified_count_at(&self, now: u64) -> usize {
        self.peers
            .iter()
            .filter(|descriptor| descriptor.verify_at(now).is_ok())
            .count()
    }
}

// ============================================
// NodeDiscoveryMessage
// ============================================

/// Bounded peer discovery gossip message.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum NodeDiscoveryMessage {
    /// Requests a valid descriptor snapshot from a peer.
    SnapshotRequest {
        /// Unix timestamp in seconds when the request was sent.
        requested_at: u64,
        /// Optional maximum number of descriptors requested.
        limit: Option<u16>,
    },
    /// Responds with a bounded descriptor snapshot.
    SnapshotResponse {
        /// Descriptor snapshot generated by the responding peer.
        snapshot: NodeBootstrapSnapshot,
    },
    /// Announces a single descriptor update.
    DescriptorAnnounce {
        /// Signed descriptor being announced.
        descriptor: SignedNodeDescriptor,
    },
    /// Announces one descriptor together with exact producer-signed Directory
    /// inclusion evidence.
    ///
    /// [DIRECTORY-GOSSIP-ADMISSION 2026-07-27 by Codex] This append-only
    /// variant is transport evidence, not an authority token. Receivers must
    /// independently retain and audit the exact `producer` / `block_hash`
    /// anchor before admitting `proof.descriptor`. The duplicated
    /// `descriptor_hash` is an explicit request/response contract boundary and
    /// must match the proof commitment.
    DirectoryDescriptorAnnounceV1 {
        /// Original Directory block producer selected by the receiver's policy.
        producer: [u8; 32],
        /// Exact producer-signed block hash selected by the receiver.
        block_hash: [u8; 32],
        /// Exact authenticated descriptor commitment digest.
        descriptor_hash: [u8; 32],
        /// Compact producer-signed inclusion proof carrying the descriptor.
        proof: DirectoryDescriptorInclusionProofV1,
    },
    /// Carries one canonical observer-signed endpoint evidence attestation.
    ///
    /// This transport object grants no persistence, forwarding, promotion,
    /// ranking, routeability, readiness, quorum, or economic authority.
    EndpointEvidenceAttestationV1 {
        /// Exact fixed-width canonical ADAT V1 frame.
        attestation_frame: Vec<u8>,
    },
}

/// Encodes a discovery gossip message using bounded bincode.
///
/// # Errors
/// Returns `CoreError::MalformedMessage` when serialization fails.
pub fn encode_discovery_message(message: &NodeDiscoveryMessage) -> Result<Vec<u8>, CoreError> {
    validate_endpoint_attestation_message(message)?;
    encode_bincode_bounded(message, MAX_DISCOVERY_MESSAGE_BYTES)
        .map_err(|err| CoreError::malformed(format!("discovery message encode: {err}")))
}

/// Decodes a discovery gossip message using bounded bincode.
///
/// # Errors
/// Returns `CoreError::MalformedMessage` when decoding fails.
pub fn decode_discovery_message(bytes: &[u8]) -> Result<NodeDiscoveryMessage, CoreError> {
    let message = decode_bincode_bounded(
        bytes,
        MAX_DISCOVERY_MESSAGE_BYTES,
        TrailingBytesPolicy::Reject,
    )
    .map_err(|err| CoreError::malformed(format!("discovery message decode: {err}")))?;
    validate_endpoint_attestation_message(&message)?;
    Ok(message)
}

// [ENDPOINT-ATTESTATION-TRANSPORT 2026-09-24 by Codex] The outer discovery
// ceiling must never turn a single fixed ADAT object into a large byte carrier.
fn validate_endpoint_attestation_message(message: &NodeDiscoveryMessage) -> Result<(), CoreError> {
    let NodeDiscoveryMessage::EndpointEvidenceAttestationV1 { attestation_frame } = message else {
        return Ok(());
    };
    if attestation_frame.len() != DISCOVERY_ENDPOINT_ATTESTATION_FRAME_BYTES_V1 {
        return Err(CoreError::malformed(
            "endpoint evidence attestation frame has invalid length",
        ));
    }
    let attestation = DiscoveryEndpointEvidenceAttestationV1::decode(attestation_frame)
        .map_err(|_| CoreError::malformed("endpoint evidence attestation frame is invalid"))?;
    if attestation.encode() != *attestation_frame {
        return Err(CoreError::malformed(
            "endpoint evidence attestation frame is non-canonical",
        ));
    }
    Ok(())
}

#[cfg(test)]
mod tests;
